#auto generator section start: code
import json
import os


def getWidgets(di, widgets) :

    widgetTypes = [
        'PushButton',
        'ToolButton',
        'ProgressBar',
        'LineEdit',
        'Dial',
        'Slider',
        'CheckBox',
        'Label',
        'OpenFileButton',
        'ToolButtonWithLed',
        'ToolButtonWithProgress',
        'VerticalSlider',
        'HorizontalSlider',
        'DigitalIOControl',
        'AnalogIOControl',
        'CurrentGcodesWidget',
        'MdiLineWidget',
        'PythonConsole',
        'GCodeList',
        'SimGLWidget',
        'OffsetTable',
        'GroupBox',
        'Frame',
        'TabWidget',
        'ScrollArea',
        'Splitter',
        'FreeLayout',
        'HorizontalLayout',
        'VerticalLayout',
        'GridLayout',
        'FormLayout'
    ]

    if "typeStr" in di and "id" in di :
        typeStr = di["typeStr"].strip().replace(" ", "")
        if typeStr in widgetTypes:
            widgets.append( [typeStr, di["id"]] )
    if "children" in di :
        for i in di['children'] :
            getWidgets(i, widgets)
    if "layout" in di :
        if "children" in di["layout"] :
            for i in di["layout"]["children"] :
                getWidgets(i, widgets)
    if "widgets" in di and "widgets" in di["widgets"]:
        for i in di["widgets"]["widgets"] :
            getWidgets(i, widgets)

def getScreenGuiFilePath( comm ):
    return getScriptsPath() + "/../../../screens/" + getScreenName( comm ) + "/gui.csscr"

def getScriptsPath():
    return os.path.dirname(os.path.realpath(__file__))

def getScreenName( comm ) :
    return comm.sendAndWait( "getScreenName:" )

def getUserWidgets( comm ) :
    widgets = []
    filePath = getScreenGuiFilePath( comm )
    try :
        with open(filePath, "r", encoding="utf-8") as f:
            data = json.load( f )
        getWidgets(data, widgets)
    except :
        print("Can't open file: " + filePath)
    return widgets


def generateGui( comm ) :

    filePath = getScriptsPath() + "/___GUI.py"
    try:
        f = open( filePath, "w", encoding="utf-8" )
    except Exception:
        raise( "Can't open file" + filePath )
    f.write("""from enum import Enum \n""")
    f.write(""" \n""")
    f.write("""class Gui(object) : \n""")
    f.write(""" \n""")
    f.write("""  class WidgetType(Enum) : \n""")
    f.write("""    PushButton = 0 \n""")
    f.write("""    ToolButton = 1 \n""")
    f.write("""    ProgressBar = 2 \n""")
    f.write("""    LineEdit = 3 \n""")
    f.write("""    Dial = 4 \n""")
    f.write("""    Slider = 5 \n""")
    f.write("""    CheckBox = 6 \n""")
    f.write("""    Label = 7 \n""")
    f.write("""    OpenFileButton = 8 \n""")
    f.write("""    ToolButtonWithLed = 9 \n""")
    f.write("""    ToolButtonWithProgress = 10 \n""")
    f.write("""    VerticalSlider = 11 \n""")
    f.write("""    HorizontalSlider = 12 \n""")
    f.write("""    DigitalIOControl = 13 \n""")
    f.write("""    AnalogIOControl = 14 \n""")
    f.write("""    CurrentGcodesWidget = 15 \n""")
    f.write("""    MdiLineWidget = 16 \n""")
    f.write("""    PythonConsole = 17 \n""")
    f.write("""    GCodeList = 18 \n""")
    f.write("""    SimGLWidget = 19 \n""")
    f.write("""    OffsetTable = 20 \n""")
    f.write("""    GroupBox = 21 \n""")
    f.write("""    Frame = 22 \n""")
    f.write("""    TabWidget = 23 \n""")
    f.write("""    ScrollArea = 24 \n""")
    f.write("""    Splitter = 25 \n""")
    f.write("""    FreeLayout = 26 \n""")
    f.write("""    HorizontalLayout = 27 \n""")
    f.write("""    VerticalLayout = 28 \n""")
    f.write("""    GridLayout = 29 \n""")
    f.write("""    FormLayout = 30 \n""")
    f.write(""" \n""")
    f.write("""  def __init__(self, comm) : \n""")
    f.write("""    self.comm = comm \n""")
    f.write("""    self.createObjects() \n""")
    f.write(""" \n""")
    f.write("""  def getIds(self) : \n""")
    f.write("""    return [i for i in self.comm.sendAndWait( "gui_getWidgetsId:" ).split(";")] \n""")
    f.write(""" \n""")
    f.write("""  class Widget(object) : \n""")
    f.write(""" \n""")
    f.write("""    def __init__(self, name, comm) : \n""")
    f.write("""      self.name = name \n""")
    f.write("""      self.comm = comm \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      return [] \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      return [] \n""")
    f.write(""" \n""")
    f.write("""    def executeOutput( self, outputName : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":" + outputName ) \n""")
    f.write(""" \n""")
    f.write("""    def setAttribute( self, attribName : str, value ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":" + attribName + ":"+ type(value).__name__ +":" + str(value) ) \n""")
    f.write(""" \n""")
    f.write("""    def getAttribute( self, attribName : str ) : \n""")
    f.write("""      res = self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":" + attribName ) \n""")
    f.write("""      pos = res.find(":") \n""")
    f.write("""      if pos < 0: \n""")
    f.write("""        raise "Attribute type error" \n""")
    f.write("""      t = res[:pos] \n""")
    f.write("""      val = res[pos+1:] \n""")
    f.write("""      if t == "int": \n""")
    f.write("""        return int(val) \n""")
    f.write("""      elif t == "float": \n""")
    f.write("""        return float(val) \n""")
    f.write("""      elif t == "bool": \n""")
    f.write("""        return bool(val) \n""")
    f.write("""      elif t == "str": \n""")
    f.write("""        return str(val) \n""")
    f.write("""      else: \n""")
    f.write("""        raise "Attribute type error" \n""")
    f.write(""" \n""")
    f.write("""  class PushButton(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.PushButton \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""        "clicked", \n""")
    f.write("""        "pressed", \n""")
    f.write("""        "released", \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def executeClickedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":clicked") \n""")
    f.write(""" \n""")
    f.write("""    def executePressedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":pressed") \n""")
    f.write(""" \n""")
    f.write("""    def executeReleasedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":released") \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class ToolButton(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.ToolButton \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""        "clicked", \n""")
    f.write("""        "pressed", \n""")
    f.write("""        "released", \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def executeClickedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":clicked") \n""")
    f.write(""" \n""")
    f.write("""    def executePressedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":pressed") \n""")
    f.write(""" \n""")
    f.write("""    def executeReleasedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":released") \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class ProgressBar(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'value', 'type' : 'float'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.ProgressBar \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setValue( self, v : float ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":value:" + "float:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getValue( self ) -> float : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":value") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return float(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class LineEdit(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.LineEdit \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""        "returnPressed", \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def executeReturnPressedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":returnPressed") \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class Dial(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'value', 'type' : 'float'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.Dial \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setValue( self, v : float ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":value:" + "float:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getValue( self ) -> float : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":value") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return float(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""        "valueChanged", \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def executeValueChangedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":valueChanged") \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class Slider(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'value', 'type' : 'float'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.Slider \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setValue( self, v : float ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":value:" + "float:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getValue( self ) -> float : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":value") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return float(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""        "valueChanged", \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def executeValueChangedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":valueChanged") \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class CheckBox(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'checkboxstate', 'type' : 'bool'}, \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.CheckBox \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setCheckboxState( self, v : bool ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":checkboxstate:" + "bool:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getCheckboxState( self ) -> bool : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":checkboxstate") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return bool(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""        "stateChanged", \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def executeStateChangedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":stateChanged") \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class Label(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.Label \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class OpenFileButton(ToolButton) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.OpenFileButton \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class ToolButtonWithLed(ToolButton) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'ledstate', 'type' : 'bool'}, \n""")
    f.write("""        {'name' : 'ledinterval', 'type' : 'int'}, \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.ToolButtonWithLed \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setLedState( self, v : bool ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":ledstate:" + "bool:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def setLedInterval( self, v : int ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":ledinterval:" + "int:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getLedState( self ) -> bool : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":ledstate") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return bool(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getLedInterval( self ) -> int : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":ledinterval") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return int(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class ToolButtonWithProgress(ToolButton) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'value', 'type' : 'float'}, \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.ToolButtonWithProgress \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setValue( self, v : float ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":value:" + "float:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getValue( self ) -> float : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":value") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return float(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class VerticalSlider(Slider) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'value', 'type' : 'float'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.VerticalSlider \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setValue( self, v : float ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":value:" + "float:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getValue( self ) -> float : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":value") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return float(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class HorizontalSlider(Slider) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'value', 'type' : 'float'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.HorizontalSlider \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setValue( self, v : float ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":value:" + "float:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getValue( self ) -> float : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":value") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return float(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class DigitalIOControl(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""        {'name' : 'state', 'type' : 'bool'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.DigitalIOControl \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def setState( self, v : bool ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":state:" + "bool:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getState( self ) -> bool : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":state") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return bool(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""        "stateChanged", \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def executeStateChangedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":stateChanged") \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class AnalogIOControl(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""        {'name' : 'text', 'type' : 'str'}, \n""")
    f.write("""        {'name' : 'value', 'type' : 'float'}, \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.AnalogIOControl \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def setText( self, v : str ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":text:" + "str:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def setValue( self, v : float ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_setAttribute:" + self.name + ":value:" + "float:" + str(v)  ) \n""")
    f.write(""" \n""")
    f.write("""    def getText( self ) -> str : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":text") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return str(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getValue( self ) -> float : \n""")
    f.write("""      res = (self.comm.sendAndWait( "gui_getAttribute:" + self.name + ":value") ) \n""")
    f.write("""      resSplit = res.split(":") \n""")
    f.write("""      return float(":".join(resSplit[1:])) \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""        "valueChanged", \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def executeValueChangedOutput( self ) : \n""")
    f.write("""      self.comm.sendAndWait( "gui_executeOutput:" + self.name + ":valueChanged") \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class CurrentGcodesWidget(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.CurrentGcodesWidget \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class MdiLineWidget(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.MdiLineWidget \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class PythonConsole(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.PythonConsole \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class GCodeList(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.GCodeList \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class SimGLWidget(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.SimGLWidget \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class OffsetTable(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.OffsetTable \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class GroupBox(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.GroupBox \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class Frame(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.Frame \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class TabWidget(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.TabWidget \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class ScrollArea(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.ScrollArea \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class Splitter(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.Splitter \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class FreeLayout(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.FreeLayout \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class HorizontalLayout(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.HorizontalLayout \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class VerticalLayout(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.VerticalLayout \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class GridLayout(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.GridLayout \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""  class FormLayout(Widget) : \n""")
    f.write(""" \n""")
    f.write("""    def getAttributes(self) : \n""")
    f.write("""      parentAttributes = super().getAttributes() \n""")
    f.write("""      thisClassAttributes =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentAttributes + thisClassAttributes \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write("""    def getType(self) : \n""")
    f.write("""      return Gui.WidgetType.FormLayout \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write("""    def getOutputs(self) : \n""")
    f.write("""      parentOutputs = super().getOutputs() \n""")
    f.write("""      thisClassOutputs =  [ \n""")
    f.write("""      ] \n""")
    f.write("""      res = parentOutputs + thisClassOutputs \n""")
    f.write("""      return res \n""")
    f.write(""" \n""")
    f.write(""" \n""")
    f.write(""" \n""")

    f.write('  def createObjects( self ) :\n')
    for i in getUserWidgets( comm ) :
        idStr = i[1].replace(' ', '_')
        f.write('    self.'+ idStr +' = Gui.'+ i[0] +'("'+ idStr +'", self.comm)\n')
    f.close()

generateGui( d.getComm() )

#auto generator section end: code
